### ISSUE TITLE
6901.6902.me72.xml Optimal Ignition Table's strange RPM's from 2123 to 2372 ?

### ISSUE THREAD

**Issue by Wiw3K** [zarboz/BMW-XDFs#11]
RPM in those tables are from 2123 to 2372 are those correct ? where are other RPM's

**Comment by zarboz** [comment]
Which file are you dealing with ?

**Comment by zarboz** [comment]
That way I can trouble shoot the right thing for you

**Comment by Wiw3K** [comment]
Found out in winols and compared to my bin and Your xdf - but have to manually put rows/cols , base offset is 10000 for fullread in TunerPro as i have.
![optimal ignition table bank 1](https://user-images.githubusercontent.com/11250229/60385742-d3249600-9a8c-11e9-978c-d97dc7ce4a63.png)

**Comment by zarboz** [comment]
Please refer to the wiki on how to choose the right xdf for your dme once you confirm you’re using the right xdf 
Then report if still different

**Comment by Wiw3K** [comment]
I am using right XDF for my software version, take a look:
![SW](https://user-images.githubusercontent.com/11250229/60385810-087db380-9a8e-11e9-8fad-02054104d987.png)
![xml](https://user-images.githubusercontent.com/11250229/60385812-0b78a400-9a8e-11e9-8118-05747c15147f.png)

XDF Name is: 6901.6902.ME72.xdf

**Comment by zarboz** [comment]
That comment section is old I need to updated it 
 Please download the most recent file directly from the github rather than from the releases page 

I will inspect this soon

**Comment by zarboz** [comment]
I don’t have my laptop with me I’ll have to refer to the table but I’m pretty sure that one uses an internal address for the RPM registers

**Comment by Wiw3K** [comment]
Looks like Your RPM table is wrong, i made it hard coded without pre-defined RPM values and it works well, already made pop bang stage 1 :) Look @ WinOLS @ this table.

**Comment by zarboz** [comment]
I need to address the offsets not being internally mapped I will work on this

**Comment by Wiw3K** [comment]
Ok, temporary fix for this is define RPM values like i posted, it works. looking for FKSTT for 6901 & 6902 :)

**Comment by zarboz** [comment]
through some discussion over private message it has come to my attention that many maps are not accurate for 6901/2 

I will probably put all existing xdf in defunct folder and then start a new XDF based around a 6901/2 binary

**Comment by Wiw3K** [comment]
When i will be at home ill send You my xdf

wt., 20 sie 2019, 21:49 użytkownik Bryan Smith <notifications@github.com>
napisał:
