### ISSUE TITLE
Idle map offsets on 5A01_v2 XDF

### ISSUE THREAD

**Issue by Spirit-Force** [zarboz/BMW-XDFs#6]
It would appear the idle table offsets are incorrect at least with ZB: 7539336 (ECE)

**Comment by zarboz** [comment]
Started project in regards to this issue. Will close issue once project is complete

**Comment by zarboz** [comment]
@Spirit-Force  are you able to submit a copy of your binary to me somehow ? all the tables line up with donor 5a01 v2

can you also verify that you do not use the "small tables" version

**Comment by Spirit-Force** [comment]
@zarboz  You should have a google drive link to my 64KB read. Also included a screen shot from TunerPro

**Comment by zarboz** [comment]
@Spirit-Force  is this the most recent software version? Just curious if it is I will go ahead and rebase 5a01 to this

**Comment by Spirit-Force** [comment]
@zarboz It should be. I check EK726.HIS and BMW official ETK. All show that to be the latest for -99 ECE 540

**Comment by Spirit-Force** [comment]
Double check the EK726.HIS and it shows that 7539366 might be superceeded by 7539326. I check this out later this evening.

**Comment by zarboz** [comment]
Roger that I will rebase for 5a01

**Comment by Spirit-Force** [comment]
That is the newest according to BMW official ETK, ISTA-P and WinKFP. Not sure why EK726.HIS shows 7539326 as update.

**Comment by zarboz** [comment]
@Spirit-Force  I rebased the xdf and its work in progress RN

**Comment by zarboz** [comment]
@Spirit-Force  I will try to work on this some more this week I have been busy with life stuff

**Comment by Spirit-Force** [comment]
@zarboz No worries man. Everyone got a life and that comes first, I've also been busy.

**Comment by zarboz** [comment]
@spirit-force I have made some progress I’m about 60% done updating the v3 WIP file to match your binary version

**Comment by Spirit-Force** [comment]
@zarboz That's great news. I've been working on Arduino based ethanol content analyzer.

**Comment by zarboz** [comment]
I think your important things to mess with are going to be 

Fuel injection maps
Lambda on/off (might need to turn feedback off for things to work right)
that SHOULD be it....


I wanna say those items are done already you can check what I have finished in teh projects page I keep those updated well

**Comment by Spirit-Force** [comment]
Regarding fuel injection maps, I'll need to adjust the cold start injection amount. That becomes an issue when the temps drop below 50F. I took a look at winols project for x5 4.4 floting around and there was FKSTT . I think that might be the map I need to adjust to get the cold start injection to needed level (or is there another map I should adjust?). Issue with colder temps and E85 is that the engine is pretty much started with the 15% of gasoline in E85 (ethanol takes a lot more energy (heat to vaporize than gasoline). Thus the injection for cold starting needs to probably be tripled for freezing temps. 

I've run over 500 miles with E85 now. Car runs fine. When the temps drop below 60F starting isn't as smooth with E85.

**Comment by zarboz** [comment]
I can try to setup FKSTT for you to manipulate cold start stuff

I am super curious your alterations to run E85

**Comment by zarboz** [comment]
FKSTT is defined and updated in the wip xdf for you to play with

**Comment by Spirit-Force** [comment]
The current alteration is bigger injectors. On to do list is a E85 compatible fuel pump. I loaded the xdf, but the map doesn't look like right. The first picture is how the updated xdf shows the FKSTT and the lower is FKSTT from the winols x5 4.4 floting arouind.
https://drive.google.com/open?id=1goFZJ3CJUKiuxeuPz2_sghksazxohWzx
https://drive.google.com/open?id=123J3rliNHDVjyyeljPWKL1qBq1whSj_b

**Comment by zarboz** [comment]
yes but the offsets align even though the map contents are not the same

it could be due to evap systems or LDP vs DMTL etc

**Comment by zarboz** [comment]
you can always use my offsets i have found in the win OLS file or you can try to align the OLS to the stock binary if you're familiar with winols

**Comment by Spirit-Force** [comment]
I'm not really familiar with winols, this is my first time tuning an ecu like this. I do mainly diag, stock software updates, retrofits, map updates, coding,  etc. etc. I'll take a look when I get round to it. Been kinda busy lately, the weekend I was at my summer cottage for the midsummer celebration with friends.

**Comment by Spirit-Force** [comment]
Thank you anyway, you've helped me alot with this stuff.

**Comment by zarboz** [comment]
I do beleive the map is proper even though the contents differe slightly 

the offests are all the same pre amble and post hex characters so the "map" is in the right definition location for our vesion

its just highly possible it changed due to version changes (map contents)


just refer to function sheet for the map information and then you can kind of gauge how your changes should look inside the map

**Comment by zarboz** [comment]
nah i hd them wrong i am trying to figure out where they are now :-D

**Comment by zarboz** [comment]
SO I think our binary version only has 11 slots as where the OLS has 12 (at least thats how the hex looks)

so i have tried to define it... I think the contents are proper Try it out and let me know

**Comment by Spirit-Force** [comment]
Now it looks proper. It will be a while before I can give it proper test because it's summer and hopefully we don't get any cold spells. Anyways what tool do you use to calculate the checksums on these ecu's? Just let the galletto to do it?

**Comment by zarboz** [comment]
I use Ultimo checksum corrector it is included in the main folders of the github so you can correct your own checksums .... i might have wrote a wiki entry for it i cant recall

**Comment by Spirit-Force** [comment]
Tried to d/l what with GitZip, but got "API rate limit exceeded". Downloaded it from a tuning forum so no issues there. Seems simple enough to use.
